[package]
name = "kvs"
version = "0.1.0"
author = ["Nitish Sharma"]
description = "A key value store"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
